from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from ..dependencies import current_user_id
from ..schemas import CareerPipelineRequest, CareerProfileAnalyzeRequest, ProfileUpdate
from ..services.ai_service import analyze_career_profile, run_career_pipeline, save_career_profile
from ..services.storage import save_upload
from services.repository import repository, supabase_insert
from ..config import get_settings

router = APIRouter(prefix='/profile', tags=['profile'])
@router.get('')
async def get_profile(user_id: str = Depends(current_user_id)):
    return repository.records.get(user_id, {'id': user_id, 'skills': [], 'onboarding_completed': False})
@router.patch('')
async def update_profile(payload: ProfileUpdate, user_id: str = Depends(current_user_id)):
    record = repository.records.setdefault(user_id, {'id': user_id, 'user_id': user_id})
    record.update(payload.model_dump(mode='json', exclude_none=True)); return record
@router.post('/resumes', status_code=201)
async def upload_resume(file: UploadFile = File(...), user_id: str = Depends(current_user_id)):
    if file.content_type != 'application/pdf': raise HTTPException(415, 'Only PDF resumes are supported')
    try: stored = await save_upload(file, user_id, 'resumes')
    except ValueError as exc: raise HTTPException(413, str(exc)) from exc
    return repository.create('resume', user_id, {'file': stored}, 'uploaded')

@router.post('/analyze')
async def analyze_profile(payload: CareerProfileAnalyzeRequest, user_id: str = Depends(current_user_id)):
    profile = await analyze_career_profile(payload.resume_text, payload.linkedin_text)
    return await save_career_profile(user_id, profile)

@router.post('/pipeline')
async def run_pipeline(payload: CareerPipelineRequest, user_id: str = Depends(current_user_id)):
    result = await run_career_pipeline(user_id, payload.resume_text, payload.linkedin_text, payload.job_description)
    if get_settings().supabase_url and get_settings().supabase_service_role_key:
        target = await supabase_insert('job_targets', {'user_id': user_id, 'company_name': result['target_profile'].get('company', 'Target company'), 'website_url': 'https://pipeline.local', 'role_title': result['target_profile'].get('role'), 'job_description': payload.job_description, 'company_context': result['target_profile'], 'analysis_status': 'completed'})
        career = await supabase_insert('career_profiles', {'user_id': user_id, 'candidate_name': result['career_profile'].get('candidate_name', 'Candidate'), 'summary': result['career_profile'].get('summary', ''), 'education': result['career_profile'].get('education', []), 'skills': result['career_profile'].get('skills', []), 'experience': result['career_profile'].get('experience', []), 'projects': result['career_profile'].get('projects', []), 'achievements': result['career_profile'].get('achievements', []), 'certifications': result['career_profile'].get('certifications', [])})
        target_profile = await supabase_insert('target_profiles', {'user_id': user_id, 'job_target_id': target['id'], **{k: result['target_profile'].get(k) for k in ('company','role','seniority','responsibilities','required_skills','preferred_skills','soft_skills','experience_requirements','education_requirements','keywords','signals')}})
        match_payload = {k: result['job_match'].get(k) for k in ('match_score', 'strengths', 'skill_gaps', 'recommendations')}
        match_payload.update({'user_id': user_id, 'job_target_id': target['id'], 'evidence': result['job_match'].get('evidence', [])})
        match = await supabase_insert('job_matches', match_payload)
        recommendation_payload = {
            'user_id': user_id,
            'category': 'skills',
            'title': 'Career recommendations',
            'content': 'Prioritized actions generated by the Recommendation Agent.',
            'evidence': {'rationale': result['recommendations'].get('rationale', [])},
            'recommendation_data': result['recommendations'],
            'status': 'pending',
        }
        recommendation = await supabase_insert('recommendations', recommendation_payload)
        result['persisted'] = {'career_profile': career['id'], 'target_profile': target_profile['id'], 'job_match': match['id'], 'recommendations': recommendation['id']}
    else:
        result['persisted'] = {'career_profile': repository.save_agent_output('career_profile', user_id, result['career_profile'])['id'], 'target_profile': repository.save_agent_output('target_profile', user_id, result['target_profile'])['id'], 'job_match': repository.save_agent_output('job_match', user_id, result['job_match'])['id'], 'recommendations': repository.save_agent_output('recommendation', user_id, result['recommendations'])['id']}
    return result
